export const data = [
    {
        id: "1",
        title: "John Wick",
        year: "2014",
        description: "this is a movie description",
        rating: "7.4/10",
        genre: "Thriller",
        category: "series",
        trending: false,
        image: "./images/jhonwick.jpg"
    },
    {
        id: "2",
        title: "Dunkirk",
        year: "2017",
        description: "this is a movie description",
        rating: "7.8/10",
        genre: "War/Action",
        category: "movie",
        trending: false,
        image: "./images/dunkirk.jpg"
    },
    {
        id: "3",
        title: "The Expendables",
        year: "2010",
        description: "this is a movie description",
        rating: "6.4/10",
        genre: "Action",
        category: "series",
        trending: false,
        image: "./images/expandables1.jpg"
    },
    {
        id: "4",
        title: "Gravity",
        year: "2013",
        description: "this is a movie description",
        rating: "7.7/10",
        genre: "Sci-fi",
        category: "movie",
        trending: false,
        image: "./images/gravity.jpg"
    },
    {
        id: "5",
        title: "Hera Pheri",
        year: "2000",
        description: "this is a movie description",
        rating: "8.1/10",
        genre: "Comedy",
        category: "series",
        trending: false,
        image: "./images/herapheri.jpg"
    },
    {
        id: "6",
        title: "The Transporter",
        year: "2002",
        description: "this is a movie description",
        rating: "6.8/10",
        genre: "Thriller",
        category: "series",
        trending: false,
        image: "./images/transporter.jpg"
    },
    {
        id: "7",
        title: "1917",
        year: "2019",
        description: "this is a movie description",
        rating: "6.8/10",
        genre: "War/Drama",
        category: "movie",
        trending: false,
        image: "./images/1917.jpeg"
    },
    {
        id: "8",
        title: "3 Idiots",
        year: "2009",
        description: "this is a movie description",
        rating: "8.4/10",
        genre: "Comedy",
        category: "movie",
        trending: false,
        image: "./images/3idiots.jpg"
    },
    {
        id: "9",
        title: "Interstellar",
        year: "2014",
        description: "this is a movie description",
        rating: "8.4/10",
        genre: "Sci-fi",
        category: "movie",
        trending: true,
        image: "./images/interstellar.jpg"
    },
    {
        id: "10",
        title: "Hacksaw Ridge",
        year: "2016",
        description: "this is a movie description",
        rating: "8.1/10",
        genre: "War/Drama",
        category: "movie",
        trending: false,
        image: "./images/hacksawridge.jpg"
    },
    {
        id: "11",
        title: "The Matrix",
        year: "1999",
        description: "this is a movie description",
        rating: "8.7/10",
        genre: "Sci-fi/Action",
        category: "series",
        trending: false,
        image: "./images/matrix.jpg"
    },
    {
        id: "12",
        title: "The Expendables 2",
        year: "2012",
        description: "this is a movie description",
        rating: "6.6/10",
        genre: "Action",
        category: "series",
        trending: false,
        image: "./images/expandables2.jpg"
    },
    {
        id: "13",
        title: "PK",
        year: "2014",
        description: "this is a movie description",
        rating: "8.1/10",
        genre: "Drama",
        category: "movie",
        trending: false,
        image: "./images/pk.jpg"
    },
    {
        id: "14",
        title: "Inception",
        year: "2010",
        description: "this is a movie description",
        rating: "8.8/10",
        genre: "Sci-fi",
        category: "movie",
        trending: true,
        image: "./images/inception.jpg"
    },
    {
        id: "15",
        title: "John Wick: Chapter 2",
        year: "2017",
        description: "this is a movie description",
        rating: "7.4/10",
        genre: "Thriller",
        category: "series",
        trending: false,
        image: "./images/jhonwick2.jpg"
    },
    {
        id: "16",
        title: "The Matrix Reloaded",
        year: "2003",
        description: "this is a movie description",
        rating: "7.2/10",
        genre: "Sci-fi/Action",
        category: "series",
        trending: false,
        image: "./images/matrix2.jpg"
    },
    {
        id: "17",
        title: "Phir Hera Pheri",
        year: "2006",
        description: "this is a movie description",
        rating: "7.1/10",
        genre: "Comedy",
        category: "series",
        trending: true,
        image: "./images/phirherapheri.jpg"
    }, {
        id: "18",
        title: "Transporter 2",
        year: "2005",
        description: "this is a movie description",
        rating: "6.3/10",
        genre: "Thriller",
        category: "series",
        trending: false,
        image: "./images/transporter2.jpg"
    },
    {
        id: "19",
        title: "The Expendables 3",
        year: "2014",
        description: "this is a movie description",
        rating: "6.1/10",
        genre: "Action",
        category: "series",
        trending: false,
        image: "./images/expandables3.jpg"
    },
    {
        id: "20",
        title: "John Wick: Chapter 3",
        year: "2019",
        description: "this is a movie description",
        rating: "7.4/10",
        genre: "Thriller",
        category: "series",
        trending: false,
        image: "./images/jhonwick3.jpg"
    },
    {
        id: "21",
        title: "The Matrix Revolutions",
        year: "2003",
        description: "this is a movie description",
        rating: "6.7/10",
        genre: "Sci-fi/Action",
        category: "series",
        trending: false,
        image: "./images/matrix3.jpg"
    },
    {
        id: "22",
        title: "Transporter 3",
        year: "2008",
        description: "this is a movie description",
        rating: "6/10",
        genre: "Thriller",
        category: "series",
        trending: false,
        image: "./images/transporter3.jpg"
    },
    {
        id: "23",
        title: "The Matrix Resurrections",
        year: "2021",
        description: "this is a movie description",
        rating: "5.7/10",
        genre: "Sci-fi/Action",
        category: "series",
        trending: false,
        image: "./images/matrix4.jpg"
    },
    {
        id: "100",
        title: "The Matrix Resurrections",
        year: "2021",
        description: "this is a movie description",
        rating: "5.7/10",
        genre: "Sci-fi/Action",
        category: "series",
        trending: false,
        image: "./images/matrix4.jpg"
    },
    {
        id: "101",
        title: "The Matrix Resurrections",
        year: "2021",
        description: "this is a movie description",
        rating: "5.7/10",
        genre: "Sci-fi/Action",
        category: "series",
        trending: false,
        image: "./images/matrix4.jpg"
    }, {
        id: "102",
        title: "The Matrix Resurrections",
        year: "2021",
        description: "this is a movie description",
        rating: "5.7/10",
        genre: "Sci-fi/Action",
        category: "series",
        trending: false,
        image: "./images/matrix4.jpg"
    },

]

